version: '3.7'

services:
  solr_suggester:
    build: .
    image: ubuntu:latest
    ports:
      - "4000:4000" 
    container_name: solr_suggester
    volumes:
    - ./:/app/
    extra_hosts:
        host.docker.internal: host-gateway
    user: ads
    entrypoint: /app/scripts/entrypoint.sh
  
  solr_search:
    build:
      context: .
      dockerfile: Dockerfile-SOLR
    image: ubuntu:latest
    ports:
      - "8983:8983" 
    container_name: solr_search
    volumes:
      - ./scripts/solrconfig.xml:/root/solrconfig.xml
      - ./:/app/local
    entrypoint: /app/local/scripts/solr_entrypoint.sh

  cors:
    image: nginx:alpine
    environment:
      BACKEND: solr_suggester:4000
    ports:
      - ${EXTERNAL_IP:-127.0.0.1}:8000:80
    volumes:
      - ./scripts/nginx-cors-proxy.conf:/etc/nginx/conf.d/default.template:ro
    command:
      - /bin/sh
      - -c
      - envsubst '$$BACKEND' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf &&
        exec nginx-debug -g 'daemon off;'