FROM ubuntu:latest

ENV UBUNTU_FRONTEND=noninteractive
USER root
RUN apt-get update && apt-get install -y ant
RUN apt-get install -y default-jre
RUN apt-get install -y default-jdk
RUN apt-get install -y git
WORKDIR "/app/"
RUN git clone https://github.com/adsabs/montysolr.git
WORKDIR "/app/montysolr"
RUN ls
RUN ant ivy-bootstrap
RUN ant build-all